### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by leeeisok** [BalestraPatrick/HapticButton#6]
Can you fix this problem，please?

**Comment by BalestraPatrick** [comment]
Can you describe the problem in more details, please?

**Comment by daviddelmonte** [comment]
Hi, I have the same issue - when I tap any of the three buttons, nothing happens, and no log messages are shown..

**Comment by daviddelmonte** [comment]
I just read another issue - 3D Touch is required. Sorry.
